trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'
  Projects: '**/*.csproj'

stages:
- stage: build
  jobs:
  - job: build
    pool:
      name: Azure Pipelines
      vmImage: 'ubuntu-latest'

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(Projects)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(Projects)
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)"'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
